---
title: "citationkey"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
Several, looked up by Carlos Salazar Martín

Primary data compiler:
Carlos Salazar Martín

Other data compilers: 
---
## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Salazar2025"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw1 <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/tabla_adiciones_CSM.xlsx"))) |> 
  rename(Taxon = `AÑADIR LOCALIDADES`,
         UTM10x10 = `...2`,
         Notas = `...3`)
dt_raw2 <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/tabla_adiciones_CSM_round2.xlsx")))

dt_raw <- rbind(dt_raw1, dt_raw2)
```


## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
  rowwise() |> 
  mutate(Taxon_ok = if_else(!grepl(" subsp. ", Taxon), 
                            stringr::word(Taxon, 1, 2),
                            paste0(stringr::word(Taxon, 1, 2)," ", 
                                   stringr::word(Taxon, which(strsplit(Taxon, split = " ")[[1]] == "subsp.")+1)))) |> 
  mutate(References = "Carlos Salazar-Martín, com.pers.") |> 
  mutate(Taxon_ok = gsub("herreraeAlgarra", "herrerae", Taxon_ok)) |> 

    select(Taxon = Taxon_ok,
           UTM10x10, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

# #check allowed values
# check_taxa(dt_modif)  #see incorrect taxa
# check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

