---
title: "Buira2020"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
The contribution of the edaphic factor as a driver of recent plant diversification in a Mediterranean biodiversity hotspot

(paper): https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2745.13527

(data): https://datadryad.org/stash/dataset/doi:10.5061/dryad.c59zw3r5r

Primary data compiler:
Toni Buira

Other data compilers: 

## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("GitHub/R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Buira2020"
dt_raw <- readr::read_csv(here(paste0("GitHub/inst/",citationkey,"/raw/Buira_endemism_dataset.csv")))
# dt_raw <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/XXXXXX.xlsx")))
```


## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
  rename(UTM10x10 = UTM.cell) |> 
  mutate(UTM1x1 = NA,
         References = "https://doi.org/10.5061/dryad.c59zw3r5r") |> 
  mutate(Taxon = gsub("_", " ", Taxon)) |> 

    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

#check allowed values
check_taxa(dt_modif)  #see incorrect taxa
check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

