---
title: "Galan2018"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
INTRODUCCIÓN A LA FLORA DE LOS BOSQUES DEL VALLE DE VALDEBEZANA (BURGOS) 
http://www.floramontiberica.org/fm/071/Flora_Montib_071_061-084_2018.pdf

Primary data compiler:
Javier Galán

Other data compilers: 

## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("GitHub/R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Galan2018"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw <- readxl::read_excel(here(paste0("GitHub/inst/",citationkey,"/raw/1632386400_Javier_Galán_AFLIBER.xlsx")),
                             sheet = "Usar")
```


## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
  mutate(References = "Galán Díaz, J. & García Antón, M. 2018. Introducción a la flora de los bosques del valle de Valdebezana (Burgos). Flora Montiberica 71: 61-84 (VII-2018)") |> 
  mutate(Taxon = gsub("  ", " ", Taxon)) |> 


    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

#check allowed values
check_taxa(dt_modif)  #see incorrect taxa
check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

