---
title: "Picornell2022"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
Picornell-Segura, Eulàlia. (2022). Catálogo de flora de la cuenca endorreica de la laguna de gallocanta. Colección de monografías de Botánica Ibérica, 24. 


Primary data compiler:
Eulàlia Picornell-Segura

Other data compilers: 

## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("GitHub/R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Picornell2022"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw <- readxl::read_excel(here(paste0("GitHub/inst/",citationkey,"/raw/Catálogo de flora Gallocanta.xlsx")), sheet = "Nuevas citas")
```


## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
  rename(Taxon = Especie_AFLIBER,
         UTM1x1 = `UTM 1x1`,
         UTM10x10 = `UTM 10x10`,
         References = `Picornell-Segura, Eulàlia. (2022). Catálogo de flora de la cuenca endorreica de la laguna de gallocanta. Colección de monografías de Botánica Ibérica, 24.`) |> 
  
    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

#check allowed values
check_taxa(dt_modif)  #see incorrect taxa
check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("GitHub/inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

