---
title: "FM88_Moreno2025"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Data origin reference:**\
González Ortega, D., E. Álvarez Gómez, J. Peláez Blanco, R. Sánchez Fernández, N. Gallego Rojas & J. García Guerra (2024). Atlas de las orquídeas silvestres de la ZEC Humada-Peña Amaya (Burgos). Flora Montiberica 88: 3-30.

<https://github.com/iramosgutierrez/AFLIBER_update/issues/22>

**Primary data compiler:**\
Juan Carlos Moreno Saiz

**Other data compilers:**

## Notes

-   

## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```

## Load dataset

```{r}
citationkey <- "FM88_Moreno2025"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/CitasOrquideas_Atlas_ZEC_Burgos_Fl.Montiberica.88.xls"))) |> 
  rename("UTM10x10" = `...3`)
```

## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
  rename(References = Referencia) |> 


    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```

## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

#check allowed values
# check_taxa(dt_modif)  #see incorrect taxa
# check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```

```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```

## Session info

```{r}
sessioninfo::session_info()
```
