---
title: "Alfaro2024"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
Herbario LEB
2019-2024

Primary data compiler:
Estrella Alfaro-Saiz

Other data compilers: 

## Notes

- Several occurrences to erase!


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Alfaro2024"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw_1 <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/Estrella_Alfaro_06-2024.xlsx")), sheet = 2)
dt_raw_2 <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/LEB-2019.xlsx"))) |> 
  select(GENERO, HIB, ESPECIE, , INFRANK, INFRA,IDQUAL, UTM) 


```


## Modify dataset

```{r}
#modify variables
dt_modif_1 <- dt_raw_1 |> 
  mutate(UTM1x1 = gsub("---", NA, UTM1x1))

dt_modif_2 <- dt_raw_2 |> 
  filter(is.na(IDQUAL)) |> 
  filter(HIB =="_") |> 
  filter(UTM!="_") |> 
  mutate(Taxon = ifelse(INFRANK == "subsp.",
                        paste0(GENERO, " ", ESPECIE, " ", INFRA),
                        paste0(GENERO, " ", ESPECIE)
                        )) |> 
  mutate(UTM = gsub(" ", "", UTM)) |> 
  filter(substr(UTM, 1, 3) %in% c("29S", "29T", "30S", "30T", "31S", "31T")) |> 
  mutate ( nchar = nchar(UTM)) |> 
  mutate(UTM10x10 =case_when(nchar(UTM)== 7 ~ UTM,
                             nchar(UTM)== 9 ~ paste0(substr(UTM, 1, 6), substr(UTM, 8, 8)),
                             nchar(UTM)==11 ~ paste0(substr(UTM, 1, 6), substr(UTM, 9, 9)),
                             nchar(UTM)==13 ~ paste0(substr(UTM, 1, 6), substr(UTM, 10, 10)),
                             nchar(UTM)==15 ~ paste0(substr(UTM, 1, 6), substr(UTM, 11, 11)),
                             nchar(UTM)==17 ~ paste0(substr(UTM, 1, 6), substr(UTM, 12, 12)),
                             nchar(UTM)==19 ~ paste0(substr(UTM, 1, 6), substr(UTM, 13, 13)))) |> 
  
  mutate(UTM1x1 =case_when(nchar(UTM)== 9 ~ UTM,
                           nchar(UTM)==11 ~ paste0(substr(UTM, 1, 7), substr(UTM, 9, 10)),
                           nchar(UTM)==13 ~ paste0(substr(UTM, 1, 7), substr(UTM, 10, 11)),
                           nchar(UTM)==15 ~ paste0(substr(UTM, 1, 7), substr(UTM, 11, 12)),
                           nchar(UTM)==17 ~ paste0(substr(UTM, 1, 7), substr(UTM, 12, 13)),
                           nchar(UTM)==19 ~ paste0(substr(UTM, 1, 7), substr(UTM, 13, 14))
  )) |> 
  mutate(References = "https://doi.org/10.15470/j3rugb") |> 
                           

    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)

dt_modif <- dt_modif_1 |> 
  bind_rows(dt_modif_2)
```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

# #check allowed values
# check_taxa(dt_modif)  #see incorrect taxa
# check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

