---
title: "Guardiola2023"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
Are Mediterranean Island Mountains Hotspots of Taxonomic and Phylogenetic Biodiversity? The Case of the Endemic Flora of the Balearic Islands
https://doi.org/10.3390/plants12142640

Primary data compiler:
Moisès Guardiola

Other data compilers: 

## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Guardiola2023"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/Table S3_MoisesGuardiola.xlsx")))

utm10 <- terra::vect(here::here("data-raw/Iberian_Peninsula_10x10_Grid/Iberian_Peninsula_10x10_Grid.shp"))

```


## Modify dataset

```{r}
#modify variables
dt_spat <- dt_raw |> 
  terra::vect(geom = c("Lon", "Lat")) |> 
  set.crs("epsg:4326") |> 
  project(utm10) 




dt_modif <- dt_raw |> 
  rename(Taxon = SPECIES) |> 
  mutate( UTM10x10 = terra::extract(utm10,dt_spat)$MGRS_10km,
          UTM1x1 = NA,
          References = "https://doi.org/10.3390/plants12142640") |> 

    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

# #check allowed values
# check_taxa(dt_modif)  #see incorrect taxa
# check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

