---
title: "Salazar2024"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data origin reference:
https://doi.org/10.15470/wiadvo
4.654 occurrences of letters B & C to upload to GBIF 

Primary data compiler:
Carlos Salazar Mendías

Other data compilers: 

## Notes

-


## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```


## Load dataset

```{r}
citationkey <- "Salazar2024"
# dt_raw <- readr::read_csv(here(paste0("inst/",citationkey,"/raw/XXXXXX.csv")))
dt_raw <- readxl::read_excel(here(paste0("inst/",citationkey,"/raw/herbario JAEN 2024_extraido.xlsx")))
```


## Modify dataset

```{r}
#modify variables
dt_modif <- dt_raw |> 
    mutate(Taxon = ifelse(is.na(subespecie),
                        paste0(Género, " ", especie),
                        paste0(Género, " ", especie, " ", subespecie))) |> 
  mutate(Coordenadas = ifelse(Coordenadas == "30TF9376", "30STF9376", Coordenadas)) |> 

  mutate("UTM1x1" = ifelse(nchar(Coordenadas) == 9, Coordenadas, NA)) |> 
  mutate("UTM10x10" = case_when(nchar(Coordenadas) == 7 ~ Coordenadas,
                                nchar(Coordenadas) == 9 ~ paste0(substr(Coordenadas, 1, 6),substr(Coordenadas, 8, 8))
                                )) |> 
  filter(!is.na(UTM10x10)) |> 
  filter(substr(UTM10x10, 1,3) %in% c("29S", "29T","30S", "30T", "31S", "31T")) |> 
  mutate(References = "https://doi.org/10.15470/wiadvo") |> 
    select(Taxon,
           UTM10x10, 
           UTM1x1, 
           References)


```


## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

# #check allowed values
# check_taxa(dt_modif)  #see incorrect taxa
# check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```
```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```



## Session info

```{r}
sessioninfo::session_info()
```

