---
title: "ERRORS"
author: "Ignacio Ramos-Gutiérrez" #author of the Rmd!
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Errors detected throughout AFLIBER's previous version.

Error data compilers:\
Ignacio Ramos-Gutiérrez\
Estrella Alfaro-Saiz\
Carlos Salazar\
Juan Carlos Moreno Saiz



## Notes

-   

## Packages

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tidylog)
library(terra)

source(here::here("R/AFLIBER_functions.R"))
```

## Load dataset

```{r}
afliber <- read_csv("E:/UNI/4. DOCTORADO/1. AFLIBER/4. For Publication/archivos/AFLIBER_Distributions.csv") |> 
  mutate(UTM1x1 = NA) |> 
  rename(UTM10x10 = UTM.cell)
```

## Modify dataset

```{r}


  # "Ornithogalum reverchonii"	"30SVF06"    #C.Salazar
  # "Ornithogalum reverchonii"	"30SVF0069"  #C.Salazar
  # "Ornithogalum reverchonii"	"30SVF28"    #C.Salazar
  # "Ornithogalum reverchonii"	"30SVF9969"  #C.Salazar
  # "Ornithogalum reverchonii"	"30SWH0411"  #C.Salazar

  # "Woodwardia radicans"	                  "29TQH11"  #E.Alfaro
  # "Aconitum napellus castellanus"	        "30TUK46"  #E.Alfaro
  # "Draba hispanica lebrunii"	            "29TQH26"  #E.Alfaro
  # "Draba hispanica lebrunii"	            "30TUN53"  #E.Alfaro
  # "Draba hispanica lebrunii"	            "30TUN63"  #E.Alfaro
  # "Petrocoptis pyrenaica viscosa"	        "29TQH26"  #E.Alfaro
  # "Petrocoptis pyrenaica viscosa"	        "30TTN55"  #E.Alfaro
  # "Echium cantabricum"  	                "30TUN58"  #E.Alfaro
  # "Echium cantabricum"  	                "30TUN75"  #E.Alfaro
  # "Genista sanabrensis" 	                "29TQG16"  #E.Alfaro
  # "Genista sanabrensis" 	                "29TPG84"  #E.Alfaro
  # "Genista sanabrensis" 	                "30TTN61"  #E.Alfaro
  # "Armeria rothmaleri"  	                "29TQH14"  #E.Alfaro

  # "Viola cazorlensis" "30SVG09" #I.Ramos
  # "Gyrocaryum oppositifolium" "30STG69" #I.Ramos. Disappeared population.

  # "Geranium dolomiticum"   "29TPG89"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TPH90"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TPH91"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TQH00"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TQH15"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TQH16"  #E.Alfaro & C.Acedo
  # "Geranium dolomiticum"   "29TQH25"  #E.Alfaro & C.Acedo

  # Astragalus gines-lopezii	30TUK08		Juan Carlos Moreno Saiz
  # Astragalus gines-lopezii	30TUK09		Juan Carlos Moreno Saiz
  # Epipogium aphyllum	31TBG95		Juan Carlos Moreno Saiz
  # Epipogium aphyllum	31TBG53		Juan Carlos Moreno Saiz
  # Erodium paularense	30TVL22		Juan Carlos Moreno Saiz
  # Erodium paularense	30TVL25		Juan Carlos Moreno Saiz
  # Erodium paularense	30TVL32		Juan Carlos Moreno Saiz
  # Erodium paularense	30TWK06		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TXL99		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TXM90		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TYM02		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TYM44		Juan Carlos Moreno Saiz
  # Ferula loscosii	31TBF47		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TYL43		Juan Carlos Moreno Saiz
  # Ferula loscosii	30TYL47		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TPG89		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TPH91		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TQH00		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TQH15		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TQH16		Juan Carlos Moreno Saiz
  # Geranium dolomiticum	29TQH25		Juan Carlos Moreno Saiz
  # Pilularia minuta	29TPG25		Juan Carlos Moreno Saiz
  # Quercus coccifera	30TVL54	change for 30TVK6453	Juan Carlos Moreno Saiz
  # Viola cazorlensis	30SVG09		Juan Carlos Moreno Saiz



  
afliber2 <- afliber |> 
  erase_gridcell(taxon = "Ornithogalum reverchonii", grid10 = c("30SVF06", "30SVF28")) |> 
  erase_gridcell(taxon = "Ornithogalum reverchonii", grid1 = c("30SVF0069", "30SVF9969", "30SWH0411")) |> 

  erase_gridcell(taxon = "Woodwardia radicans"          , grid10 =  "29TQH11" ) |> 
  erase_gridcell(taxon = "Aconitum napellus castellanum", grid10 =  "30TUK46" ) |> 
  erase_gridcell(taxon = "Draba hispanica lebrunii"	    , grid10 =  "29TQH26" ) |> 
  erase_gridcell(taxon = "Draba hispanica lebrunii"	    , grid10 =  "30TUN53" ) |> 
  erase_gridcell(taxon = "Draba hispanica lebrunii"	    , grid10 =  "30TUN63" ) |> 
  erase_gridcell(taxon = "Petrocoptis pyrenaica viscosa", grid10 =  "29TQH26" ) |> 
  erase_gridcell(taxon = "Petrocoptis pyrenaica viscosa", grid10 =  "30TTN55" ) |> 
  erase_gridcell(taxon = "Echium cantabricum"  	        , grid10 =  "30TUN58" ) |> 
  erase_gridcell(taxon = "Echium cantabricum"  	        , grid10 =  "30TUN75" ) |> 
  erase_gridcell(taxon = "Genista sanabrensis" 	        , grid10 =  "29TQG16" ) |> 
  erase_gridcell(taxon = "Genista sanabrensis" 	        , grid10 =  "29TPG84" ) |> 
  erase_gridcell(taxon = "Genista sanabrensis" 	        , grid10 =  "30TTN61" ) |> 
  erase_gridcell(taxon = "Armeria rothmaleri"  	        , grid10 =  "29TQH14" ) |> 
  
  erase_gridcell(taxon = "Viola cazorlensis"         , grid10 = "30SVG09" ) |> 
  erase_gridcell(taxon = "Gyrocaryum oppositifolium" , grid10 = "30STG69" ) |> 

  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TPG89") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TPH90") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TPH91") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TQH00") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TQH15") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TQH16") |> 
  erase_gridcell(taxon = "Geranium dolomiticum", grid10 = "29TQH25") |> 

  erase_gridcell(taxon = "Astragalus gines-lopezii" , grid10 = "30TUK08") |> 
  erase_gridcell(taxon = "Astragalus gines-lopezii" , grid10 = "30TUK09") |> 
  erase_gridcell(taxon = "Epipogium aphyllum"       , grid10 = "31TBG95") |> 
  erase_gridcell(taxon = "Epipogium aphyllum"       , grid10 = "31TBG53") |> 
  erase_gridcell(taxon = "Erodium paularense"       , grid10 = "30TVL22") |> 
  erase_gridcell(taxon = "Erodium paularense"       , grid10 = "30TVL25") |> 
  erase_gridcell(taxon = "Erodium paularense"       , grid10 = "30TVL32") |> 
  erase_gridcell(taxon = "Erodium paularense"       , grid10 = "30TWK06") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TXL99") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TXM90") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TYM02") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TYM44") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "31TBF47") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TYL43") |> 
  erase_gridcell(taxon = "Ferula loscosii"          , grid10 = "30TYL47") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TPG89") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TPH91") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TQH00") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TQH15") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TQH16") |> 
  # erase_gridcell(taxon = "Geranium dolomiticum"     , grid10 = "29TQH25") |> 
  erase_gridcell(taxon = "Pilularia minuta"         , grid10 = "29TPG25") |> 
  erase_gridcell(taxon = "Viola cazorlensis"        , grid10 = "30SVG09") 

  # Quercus coccifera         30TVL54	change for 30TVK6453	Juan Carlos Moreno Saiz

```

## Prepare dataset

```{r}

dt_modif$id <- 1:nrow(dt_modif)

#check allowed values
check_taxa(dt_modif)  #see incorrect taxa
check_cells(dt_modif)  #see incorrect cells

dt_check_vals <- dt_modif |> 
clean_values()


# Create dataset to compile
dt_include<- dt_check_vals |> 
  distinct(Taxon,
           UTM10x10, 
           UTM1x1, 
           References,
           id)

dt_save <- dt_modif |> 
  filter(!id %in% dt_include$id)

```

```{r}
readr::write_csv(select(dt_include, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,".csv")))

readr::write_csv(select(dt_save, -matches("id") ),
                 here(paste0("inst/",citationkey,"/data/", citationkey,"_notused.csv")))



```

## Session info

```{r}
sessioninfo::session_info()
```
